### ISSUE TITLE
PropertyFieldColorPicker unable to set alpha value 

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-fx-property-controls#52] opened 2018-04-23 21:05 UTC
#### Category
[ ] Bug

[ ] Question

Unable to set the alpha color property value in the PropertyFieldColorPicker control. Because of this when the focus is out of the property pane, the value goes back to RGB only instead of RGB**A**. 

The color control should work as shown in the below example to get the RGBA values 
https://casesandberg.github.io/react-color/ 
Note: Happens only when style: PropertyFieldColorPickerStyle.**Full**

**Comment by thechriskent** [comment] 2018-04-24 18:01
Unfortunately, I can't seem to recreate this issue (or I'm not understanding). Here is a gif of what I am seeing:

![alpha Color](https://thechriskent.files.wordpress.com/2018/04/alphacolor.gif)

Could you provide more details about the issue, specifically:
- Does this only occur when dragging the alpha slider?
- Does this only occur when editing the alpha value directly?
- Are you using Reactive Property Changes (as shown in the gif)?

Thanks!

**Comment by sprider** [comment] 2018-04-24 22:27
Hi,

The issue occurs when I close the property pane and come back to the web part. As you shown in this gif, I can not reproduce this issue when I change the value and keep the property pane open. 

Could you please let me know the tool you are using to convert the screen recording to gif? I will record and share the behavior.

**Comment by thechriskent** [comment] 2018-04-25 03:38
Thank you for the gif! This helped me recreate the issue and identify the problem. The issue occurs when the PropertyFieldColorPicker is the first (or only) property pane field and the style is set to Full.

The cause of the problem is how the ColorPicker control handles the blur event on the Hex textbox. When the Hex textbox loses focus, the value is evaluated and everything is updated. Since hex values don't represent alpha values, the alpha value is always set to 100%. This is always true and can be seen on the [UI Fabric React Component's demo page](https://developer.microsoft.com/en-us/fabric#/components/colorpicker) as well (change the alpha value, click into the hex textbox, then click out. The alpha value will be reset to 100). This is expected behavior and is inline with the UI Fabric components (even if not great).

However, the confusion occurs because when the property pane is opened, focus is set to the first input in the property pane. When a PropertyFieldColorPicker is the first field, focus is set to the Hex textbox. This results in the confusing behavior of changing the color using the sliders (all the while the focus remains in the Hex textbox) only to have the alpha value reset to 100 when the Hex textbox loses focus.

I have solved this issue by including a hidden input above the ColorPicker when the style is set to Full. This has no effect when the PropertyFieldColorPicker is not the first field in the property pane, but intercepts the focus when it is. This eliminates the confusing behavior of letting users use the sliders to configure values only to have the alpha value reset on them. Here's what it looks like with the new behavior (green click indicator circle added):

![alpha color fixed](https://thechriskent.files.wordpress.com/2018/04/alphacolorfixed.gif)

Thank you very much for bringing this to our attention!

**Comment by sprider** [comment] 2018-04-25 13:47
Hi Chris,

Thank you for your response. 

I have verified the code change with version 1.5.1-beta.3404e60 and it looks good except the first time. When I change the Alpha value for the first time it goes back to hex value. Am I using the right latest version of your code? 

Providing additional values such as R,G,B,Alpha and Hex on top of color outcome will help a lot. 
Example: https://casesandberg.github.io/react-color/
background: `rgba(${ this.properties.color.r }, ${ this.properties.color.g }, ${ this.properties.color.b }, ${ this.properties.color.a })`

**Comment by estruyf** [comment] 2018-04-25 16:00
The fix has been merged and is now available in the v1.5.1 beta. If you want to test out the beta, here you can find more information how you can do this: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/

**Comment by sprider** [comment] 2018-04-25 16:17
Looks cool and issue resolved. Thank you Chris and Elio. 

Can you do one more change? The icon we set using the iconName property is not aligned properly in the IE 11

**Chrome**
<img width="334" alt="chrome" src="https://user-images.githubusercontent.com/21008316/39258664-216fd8e4-487a-11e8-859d-289724c6e2b4.png">

**IE 11**
<img width="328" alt="ie 11" src="https://user-images.githubusercontent.com/21008316/39258691-2ca14cc0-487a-11e8-935c-ba4cbda123ae.png">

**Comment by thechriskent** [comment] 2018-04-25 16:25
Glad to hear it! Thanks again for taking the time to submit this issue!

As for the IE 11 alignment - Would you mind opening an additional issue for this one so that we can track it? Thanks!

**Closed by thechriskent** 2018-04-25 16:25 UTC
Labels: bug, in progress

**Comment by sprider** [comment] 2018-04-25 16:39
Sure, Done #56
